### ISSUE TITLE
RFC: Allow cache customization

### ISSUE THREAD

**Issue by richardsheridan** [richardsheridan/trio-parallel#12]
The current cache is one-size-fits-all, but surely someone will want to experiment with `fork` or `forkserver`, or kill WorkerProcs after a certain number of jobs, or always obtain fresh workers. If subinterpreters become a thing, they should also be a choice for users to select.

I think a nice way to do this would be with [contextvars](https://docs.python.org/3/library/contextvars.html) and a sync context manager:

```python
async def f():
    with trio_parallel.cache_scope(**options):
        await trio_parallel.run_sync(print, "using a fresh cache")
```

But certain options like telling the cache not to reuse a certain worker would be amenable to a simple keyword argument:

```python
await trio_parallel.run_sync(fib, 100, fresh_worker=True, destroy_after=True)
```

I guess these are not exclusive, but I don't want to clutter the API... so I'm leaning towards only making keyword arguments in response to specific user demands.

**Comment by richardsheridan** [comment]
Seems like an async-checkpoint-on-aexit contextmanager is a better way to go so that we can ensure all workers are reaped on unix.

**Comment by goodboy** [comment]
@richardsheridan that's exactly how `tractor` [does it inside its nurseries](https://github.com/goodboy/tractor/blob/master/tractor/_trionics.py#L203), though reaping is a lot easier when you have an IPC protocol that handles cancellation 😉
